- hosts: all
  become: yes
  vars:
    zusername: synchro
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ zusername }}"
          oh_my_zsh:
            theme: powerlevel10k
            plugins:
              - git
  post_tasks:
    - name: Clone powerlevel10k repo
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/{{ zusername }}/.oh-my-zsh/themes/powerlevel10k
        depth: 1
    - name: copy .p10k.zsh template
      ansible.builtin.copy:
        src: .p10k.zsh
        dest: /home/{{ zusername }}/.p10k.zsh
        owner: "{{ zusername }}"
        group: "{{ zusername }}"
        mode: u+rw,g-wx,o-rwx
    - name: copy .zshrc template
      ansible.builtin.copy:
        src: .zshrc
        dest: /home/{{ zusername }}/.zshrc
        owner: "{{ zusername }}"
        group: "{{ zusername }}"
        mode: u+rw,g-wx,o-rwx

    - name: Install extra-packages
      package:
        name:
          - vim
          - git
          - jq
        state: latest

    - name: craete vim themes dir
      file:
        state: directory
        path: /home/{{ zusername }}/.vim/pack/themes/start
        owner: "{{ zusername }}"
        group: "{{ zusername }}"
        mode: u+rw,g-wx,o-rwx

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/dracula/vim.git'
        dest: /home/{{ zusername }}/.vim/pack/themes/start/dracula

    - name: Update/create .vimrc
      lineinfile:
        dest: /home/{{ zusername }}/.vim/vimrc
        line: "{{ item }}"
        create: true
      with_items:
        - "packadd! dracula"
        - "syntax enable"
        - "colorscheme dracula"
        - "set nu"
        - "set showmatch"
      tags: 
        aaa
   
